name: 'Generic Security Scanner'
description: 'Runs a security tool via Docker and uploads SARIF report'
inputs:
  command:
    description: 'Command to execute inside the container'
    required: true
  report_file:
    description: 'Name of the output SARIF file'
    required: true
  tool_name:
    description: 'Name of the tool'
    required: true
  image: 
    description: 'Docker image to use'
    required: true

runs:
  using: "composite"
  steps:

    # 1. Run tool via Docker
    - name: Run Analysis Tool (${{ inputs.tool_name }})
      shell: bash
      run: |
        echo "::group::Running ${{ inputs.tool_name }}"
        
        docker run --rm \
          -v "${{ github.workspace }}:/app" \
          -w /app \
          ${{ inputs.image }} \
          ${{ inputs.command }}
          
        echo "::endgroup::"

    # 2. Upload SARIF 
    - name: Upload SARIF to GitHub Security
      uses: github/codeql-action/upload-sarif@v4
      if: always()
      with:
        sarif_file: ${{ inputs.report_file }}
        category: ${{ inputs.tool_name }}

    # # 3. Upload Report as Artifact
    # - name: Archive Report
    #   uses: actions/upload-artifact@v4
    #   if: always()
    #   with:
    #     name: scan-report-${{ inputs.tool_name }}
    #     path: ${{ inputs.report_file }}
    #     retention-days: 1