name: 'Generic Security Scanner'
description: 'Runs a security tool via Docker and uploads SARIF report'
inputs:
  command:
    description: 'Command to execute inside the container'
    required: true
  report_file:
    description: 'Name of the output SARIF file'
    required: true
  tool_name:
    description: 'Name of the tool'
    required: true
  image: 
    description: 'Docker image to use'
    required: true
  dojo_scan_type:
    description: 'Dojo Scan Type'
    required: true
  defectdojo_url:
    description: 'DefectDojo URL'
    required: true
  defectdojo_token:
    description: 'DefectDojo API Token'
    required: true
  defectdojo_product_name:
    description: 'DefectDojo Product Name'
    required: true

runs:
  using: "composite"
  steps:

    - name: Run Analysis Tool (${{ inputs.tool_name }})
      shell: bash
      continue-on-error: true
      run: |
        echo "Running ${{ inputs.tool_name }}"
        
        docker run --rm --entrypoint "" \
          -v "${{ github.workspace }}:/code" \
          -w /code \
          ${{ inputs.image }} \
          ${{ inputs.command }}
          
        echo "::endgroup::"

    - name: Upload SARIF to GitHub Security
      uses: github/codeql-action/upload-sarif@v4
      if: always()
      with:
        sarif_file: ${{ inputs.report_file }}
        category: ${{ inputs.tool_name }}

    - name: Upload to DefectDojo
      if: always()
      shell: bash
      run: |
        echo "Sending ${{ inputs.report_file }} to DefectDojo..."
        curl -X POST "${{ inputs.defectdojo_url }}/api/v2/import-scan/" \
             -H "Authorization: Token ${{ inputs.defectdojo_token }}" \
             -H "Content-Type: multipart/form-data" \
             -F "active=true" \
             -F "verified=true" \
             -F "scan_type=${{ inputs.dojo_scan_type }}" \
             -F "minimum_severity=Info" \
             -F "engagement_name=SAST-Matrix-${{ github.run_id }}" \
             -F "product_name=${{ inputs.defectdojo_product_name }}" \
             -F "file=@${{ inputs.report_file }}" \
             -F "close_old_findings=true"