name: 'Container Image Scanning'
description: 'Scans a container image using Trivy and uploads results to DefectDojo'
inputs:
  image-tag:
    description: 'The Docker image tag to scan'
    required: true
  github-token:
    description: 'GitHub Token to pull the image from GHCR'
    required: true
  defectdojo_url:
    description: 'DefectDojo API URL'
    required: true
  defectdojo_token:
    description: 'DefectDojo API Token'
    required: true
  defectdojo_product_name:
    description: 'DefectDojo Product Name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Run Trivy vulnerability scanner on Docker image
      uses: aquasecurity/trivy-action@0.35.0
      with:
        image-ref: ${{ inputs.image-tag }}
        format: 'sarif'
        output: 'trivy-image-results.sarif'
        severity: 'CRITICAL,HIGH,MEDIUM'
        ignore-unfixed: true
      continue-on-error: true

    - name: Upload Trivy results to DefectDojo
      shell: bash
      run: |
        curl -X POST "${{ inputs.defectdojo_url }}/api/v2/import-scan/" \
             -H "Authorization: Token ${{ inputs.defectdojo_token }}" \
             -H "Content-Type: multipart/form-data" \
             -F "active=true" \
             -F "verified=true" \
             -F "scan_type=Trivy Scan" \
             -F "minimum_severity=Info" \
             -F "engagement_name=Container Image Security" \
             -F "product_name=${{ inputs.defectdojo_product_name }}" \
             -F "auto_create_context=true" \
             -F "file=@trivy-image-results.sarif" \
             -F "close_old_findings=true"