inputs:
  app-port:
    description: 'The port exposed by the application container'
    required: true
  app-path:
    description: 'The context path of the application'
    required: false
    default: '/'
  image-tag:
    description: 'The exact Docker image tag to test'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Application Container
      shell: bash
      run: |
        echo "::group::Starting Immutable Container"
        PORT=${{ inputs.app-port }}
        APP_PATH=${{ inputs.app-path }}
        CLEAN_PATH=$(echo $APP_PATH | sed 's|^/||')
        
        docker run -d --name test-app -p $PORT:$PORT ${{ inputs.image-tag }}
        
        HEALTH_URL="http://localhost:$PORT/$CLEAN_PATH"
        echo "Waiting for response on $HEALTH_URL..."
        
        timeout 120 bash -c "while [[ \"\$(curl -s -o /dev/null -w ''%{http_code}'' $HEALTH_URL)\" != \"200\" && \"\$(curl -s -o /dev/null -w ''%{http_code}'' $HEALTH_URL)\" != \"302\" ]]; do sleep 5; done" || (docker logs test-app && exit 1)
        
        echo "::notice::Application is up and running!"
        echo "::endgroup::"

    - name: Run OWASP ZAP Baseline Scan (Docker)
      shell: bash
      run: |
        echo "::group::Running ZAP Baseline"
        PORT=${{ inputs.app-port }}
        APP_PATH=${{ inputs.app-path }}
        CLEAN_PATH=$(echo $APP_PATH | sed 's|^/||')
        
        TARGET_URL="http://localhost:$PORT/$CLEAN_PATH"
        chmod 777 $(pwd)
        
        docker run --rm --network host \
          -v $(pwd):/zap/wrk/:rw \
          zaproxy/zap-stable zap-baseline.py \
          -t $TARGET_URL \
          -r zap-report.html \
          -I 
        echo "::endgroup::"

    - name: Run Nuclei DAST Scan
      uses: projectdiscovery/nuclei-action@v3
      with:
        target: http://localhost:${{ inputs.app-port }}${{ inputs.app-path }}
        json-export: nuclei-report.json
        markdown-export: nuclei-report.md
        
    # - name: Upload ZAP HTML Report
    #   uses: actions/upload-artifact@v4
    #   if: always() 
    #   with:
    #     name: zap-dast-report
    #     path: zap-report.html

    - name: Cleanup Container
      if: always()
      shell: bash
      run: docker rm -f test-app || true