name: Orchestrator
on:
  workflow_call:
    inputs:
      app-port:
        description: 'Application Port to use'
        type: string
        required: true
      app-path:
        description: 'Application Path to use'
        type: string
        required: false
        default: '/'
      defectdojo_product_name:
        description: 'DefectDojo Product Name'
        type: string
        required: true
      sonar_organization:
        description: 'SonarCloud Organization'
        type: string
        required: false
        default: ''
      sonar_project_key:
        description: 'SonarCloud Project Key'
        type: string
        required: false
        default: ''
      node-version:
        description: 'Node.js Version'
        type: string
        required: false
        default: '22'
      java-version:
        description: 'JDK Version'
        type: string
        required: false
        default: '25'
      max_critical:
        description: 'Maximum allowed active Critical vulnerabilities'
        type: string
        required: false
        default: '0'
      max_high:
        description: 'Maximum allowed active High vulnerabilities'
        type: string
        required: false
        default: '0'
      fail_on_security_gate:
        description: 'Fail the pipeline if security gate thresholds are breached'
        type: boolean
        required: false
        default: true

jobs:
  # LOAD CONFIG
  load-config:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-configs.outputs.sast_matrix }}
      config: ${{ steps.get-configs.outputs.sast_config }}
      dast_matrix: ${{ steps.get-configs.outputs.dast_matrix }}
      dast_config: ${{ steps.get-configs.outputs.dast_config }}
    steps:
      - name: Fetch Pipeline Configuration
        id: get-configs
        uses: gha-sec-scans/orchestrator/.github/actions/utils/load-config@feature/refinement
        with:
          config_branch: 'feature/refinement'
          org_token: ${{ secrets.ORG_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}

  # PREFLIGHT  
  ## STATIC ANALYSIS
  static-analysis:
    name: Scan (${{ matrix.tool }})
    needs: load-config
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tool: ${{ fromJson(needs.load-config.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v6
      - name: Run Security Tool
        uses: gha-sec-scans/orchestrator/.github/actions/security/sast-template@feature/refinement
        with:
          tool_name: ${{ matrix.tool }}
          image: ${{ fromJson(needs.load-config.outputs.config)[matrix.tool].image }}
          command: ${{ fromJson(needs.load-config.outputs.config)[matrix.tool].command }}
          report_file: ${{ fromJson(needs.load-config.outputs.config)[matrix.tool].report_file }}
          dojo_scan_type: ${{ fromJson(needs.load-config.outputs.config)[matrix.tool].dojo_scan_type }}
          defectdojo_url: ${{ secrets.DEFECTDOJO_URL }}
          defectdojo_token: ${{ secrets.DEFECTDOJO_TOKEN }}
          defectdojo_product_name: ${{ inputs.defectdojo_product_name }}

  ## CodeQL
  codeql:
    name: SAST - CodeQL
    needs: load-config
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v6
      - name: Setup & Cache
        id: setup
        uses: gha-sec-scans/orchestrator/.github/actions/utils/setup@feature/refinement
        with:
          node-version: ${{ inputs.node-version }}
          java-version: ${{ inputs.java-version }}

      - name: Run CodeQL Workflow
        uses: gha-sec-scans/orchestrator/.github/actions/security/codeql-analysis@feature/refinement
        with:
          project-type: ${{ steps.setup.outputs.project-type }}
          defectdojo_url: ${{ secrets.DEFECTDOJO_URL }}
          defectdojo_token: ${{ secrets.DEFECTDOJO_TOKEN }}
          defectdojo_product_name: ${{ inputs.defectdojo_product_name }}

  ## Sonar
  sonar:
    name: SAST - SonarCloud
    needs: load-config
    if: ${{ inputs.sonar_organization != '' && inputs.sonar_project_key != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup & Cache
        id: setup
        uses: gha-sec-scans/orchestrator/.github/actions/utils/setup@feature/refinement
        with:
          node-version: ${{ inputs.node-version }}
          java-version: ${{ inputs.java-version }}

      - name: Run Sonar Workflow
        uses: gha-sec-scans/orchestrator/.github/actions/security/sonar-analysis@feature/refinement
        with:
          project-type: ${{ steps.setup.outputs.project-type }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          defectdojo_url: ${{ secrets.DEFECTDOJO_URL }}
          defectdojo_token: ${{ secrets.DEFECTDOJO_TOKEN }}
          defectdojo_product_name: ${{ inputs.defectdojo_product_name }}
          sonar-organization: ${{ inputs.sonar_organization }}
          sonar-project-key: ${{ inputs.sonar_project_key }}

  # TEST
  test:
    name: Run Tests
    needs: load-config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup & Cache
        id: setup
        uses: gha-sec-scans/orchestrator/.github/actions/utils/setup@feature/refinement
        with:
          node-version: ${{ inputs.node-version }}
          java-version: ${{ inputs.java-version }}

      - name: Run Tests (Node)
        if: steps.setup.outputs.project-type == 'node'
        run: npm test

      - name: Run Tests (Maven)
        if: steps.setup.outputs.project-type == 'maven'
        run: mvn test

  # BUILD & PUSH
  build:
    name: Build & Push Docker Image
    needs: [test, static-analysis, codeql, sonar]
    if: ${{ !cancelled() && needs.test.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Setup & Cache
        id: setup
        uses: gha-sec-scans/orchestrator/.github/actions/utils/setup@feature/refinement
        with:
          node-version: ${{ inputs.node-version }}
          java-version: ${{ inputs.java-version }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Maven Build & Push
        if: steps.setup.outputs.project-type == 'maven'
        uses: gha-sec-scans/orchestrator/.github/actions/build/maven@feature/refinement
        with:
          image-tag: ghcr.io/${{ github.repository }}:${{ github.sha }}
          defectdojo_url: ${{ secrets.DEFECTDOJO_URL }}
          defectdojo_token: ${{ secrets.DEFECTDOJO_TOKEN }}
          defectdojo_product_name: ${{ inputs.defectdojo_product_name }}

      - name: Run Node Build & Push
        if: steps.setup.outputs.project-type == 'node'
        uses: gha-sec-scans/orchestrator/.github/actions/build/node@feature/refinement
        with:
          image-tag: ghcr.io/${{ github.repository }}:${{ github.sha }}
          defectdojo_url: ${{ secrets.DEFECTDOJO_URL }}
          defectdojo_token: ${{ secrets.DEFECTDOJO_TOKEN }}
          defectdojo_product_name: ${{ inputs.defectdojo_product_name }}

  ## IMAGE SCANNING       
  image-scanning:
    name: Container Image Scanning
    needs: build
    if: ${{ !cancelled() && needs.build.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v6

      - name: Run Image Scanning
        uses: gha-sec-scans/orchestrator/.github/actions/security/image-scanning@feature/refinement
        with:
          image-tag: ghcr.io/${{ github.repository }}:${{ github.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          defectdojo_url: ${{ secrets.DEFECTDOJO_URL }}
          defectdojo_token: ${{ secrets.DEFECTDOJO_TOKEN }}
          defectdojo_product_name: ${{ inputs.defectdojo_product_name }}
          scan_type: "Trivy Image Scanning"

  # PRE-DEPLOY
  pre-deploy:
    name: DAST (${{ matrix.tool }})
    needs: [image-scanning, load-config]
    if: ${{ !cancelled() && needs.image-scanning.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    strategy:
      fail-fast: false
      matrix:
        tool: ${{ fromJson(needs.load-config.outputs.dast_matrix) }}
    steps:
      - uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run DAST Matrix Tool
        uses: gha-sec-scans/orchestrator/.github/actions/security/dast-template@feature/refinement
        with:
          tool_name: ${{ matrix.tool }}
          image: ${{ fromJson(needs.load-config.outputs.dast_config)[matrix.tool].image }}
          command: ${{ fromJson(needs.load-config.outputs.dast_config)[matrix.tool].command }}
          report_file: ${{ fromJson(needs.load-config.outputs.dast_config)[matrix.tool].report_file }}
          app-port: ${{ inputs.app-port }}
          app-path: ${{ inputs.app-path }}
          image-tag: ghcr.io/${{ github.repository }}:${{ github.sha }}
          dojo_scan_type: ${{ fromJson(needs.load-config.outputs.dast_config)[matrix.tool].dojo_scan_type }}
          defectdojo_url: ${{ secrets.DEFECTDOJO_URL }}
          defectdojo_token: ${{ secrets.DEFECTDOJO_TOKEN }}
          defectdojo_product_name: ${{ inputs.defectdojo_product_name }}

# DEPLOY
  deploy:
    name: Security Gate & Deploy
    needs: pre-deploy
    if: ${{ !cancelled() && needs.pre-deploy.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Evaluate Security Quality Gate
        uses: gha-sec-scans/orchestrator/.github/actions/security/quality-gate@feature/refinement
        with:
          defectdojo_url: ${{ secrets.DEFECTDOJO_URL }}
          defectdojo_token: ${{ secrets.DEFECTDOJO_TOKEN }}
          defectdojo_product_name: ${{ inputs.defectdojo_product_name }}
          max_critical: ${{ inputs.max_critical }}
          max_high: ${{ inputs.max_high }}
          fail_on_breach: ${{ inputs.fail_on_security_gate }}

      - name: Deploy Application
        run: |
          echo "Security Quality Gate passed! Proceeding with deployment..."